"""create messages table

Revision ID: 3bcfaf310c2b
Revises: 
Create Date: 2025-05-25 17:59:47.111949

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3bcfaf310c2b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('messages',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='Record identifier'),
    sa.Column('title', sa.String(length=250), nullable=False, comment='Message title'),
    sa.Column('category', sa.String(length=250), nullable=False, comment='Message category'),
    sa.Column('image', sa.String(length=250), nullable=True, comment='File name for associated message image'),
    sa.Column('text', sa.Text(), nullable=False, comment='Message text content'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='When the message was created'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='When the message was last updated'),
    sa.Column('deleted_at', sa.DateTime(), nullable=True, comment='Soft-delete timestamp; message hidden if set'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('messages')
    # ### end Alembic commands ###
